name: wallpaperdesing_2
description: "A new Flutter project."

publish_to: 'none'

version: 1.12.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  http: ^1.2.2
  permission_handler: ^11.3.1
  url_launcher: ^6.0.9
  fluttertoast: ^8.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
